//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChamCong
    {
        public ChamCong()
        {
            this.PhieuLuongs = new HashSet<PhieuLuong>();
        }
    
        public int MaChamCong { get; set; }
        public System.DateTime Ngay { get; set; }
        public System.DateTime ThoiGianVao { get; set; }
        public System.DateTime ThoiGianRa { get; set; }
        public int MaNV { get; set; }
        public Nullable<System.TimeSpan> SoGioLam { get; set; }
        public Nullable<System.TimeSpan> GioDiMuon { get; set; }
        public Nullable<System.TimeSpan> GioVeSom { get; set; }
        public Nullable<System.TimeSpan> GioTangCa { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<PhieuLuong> PhieuLuongs { get; set; }
    }
}
