//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataWebEntities : DbContext
    {
        public DataWebEntities()
            : base("name=DataWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ChamCong> ChamCongs { get; set; }
        public DbSet<ChucVu> ChucVus { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhongBan> PhongBans { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Role_Menu> Role_Menu { get; set; }
        public DbSet<PhieuLuong> PhieuLuongs { get; set; }
        public DbSet<NhatKyLuong> NhatKyLuongs { get; set; }
    }
}
