//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public NhanVien()
        {
            this.Accounts = new HashSet<Account>();
            this.ChamCongs = new HashSet<ChamCong>();
            this.PhieuLuongs = new HashSet<PhieuLuong>();
            this.NhatKyLuongs = new HashSet<NhatKyLuong>();
        }
    
        public int MaNV { get; set; }
        public string HotenNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public int SĐT { get; set; }
        public decimal LuongCBan { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaCV { get; set; }
        public int MaPB { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual ICollection<PhieuLuong> PhieuLuongs { get; set; }
        public virtual ICollection<NhatKyLuong> NhatKyLuongs { get; set; }
    }
}
