//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyLuong
    {
        public NhatKyLuong()
        {
            this.PhieuLuongs = new HashSet<PhieuLuong>();
        }
    
        public int IDNhatKy { get; set; }
        public int MaNV { get; set; }
        public decimal LuongCBan { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ICollection<PhieuLuong> PhieuLuongs { get; set; }
    }
}
