//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuLuong
    {
        public int MaBL { get; set; }
        public int MaNV { get; set; }
        public int IDNhatKy { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public decimal LuongCBan { get; set; }
        public decimal Luong1NgayCong { get; set; }
        public decimal HeSoTangCa { get; set; }
        public decimal Luong1hTangCa { get; set; }
        public Nullable<decimal> Thuong { get; set; }
        public Nullable<decimal> Phat { get; set; }
        public int SoNgayCong { get; set; }
        public Nullable<double> SoGioTangCa { get; set; }
        public decimal? BHYT { get; set; }
        public decimal? BHXH { get; set; }
        public decimal? Thue { get; set; }
        public decimal TongLuong { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public int MaChamCong { get; set; }
    
        public virtual ChamCong ChamCong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhatKyLuong NhatKyLuong { get; set; }
    }
}
